version: 0.2


env:
  variables:
    SOLUTION: .\sample.sln
    PACKAGE_DIRECTORY: .\sample_publish
    DOTNET_FRAMEWORK: 4.6.1


phases:
  build:
    commands:
      - dotnet nuget restore $SOLUTION -PackagesDirectory $PACKAGE_DIRECTORY
      - msbuild -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\vDOTNET_FRAMEWORK" $SOLUTION


artifacts:
  files:
    - .\sample\bin\obj\Debug\*
