version: 0.2


env:
  variables:
    SOLUTION: .\sample.sln
    PACKAGE_DIRECTORY: .\sample_publish
    DOTNET_FRAMEWORK: 4.8


phases:
  installs:
     runtime-versions:
      dotnet: $env:DOTNET_FRAMEWORK

  build:
    commands:
      - dotnet nuget help restore
      - dotnet nuget restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY
      - msbuild -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION


artifacts:
  files:
    - .\sample\bin\obj\Debug\*
