version: 0.2


env:
  variables:
    SOLUTION: .\sample.sln
    PACKAGE_DIRECTORY: .\sample_publish
    DOTNET_FRAMEWORK: 4.8


phases:
  build:
    commands:
      - '& "C:\ProgramData\chocolatey\bin\NuGet.exe" restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION'


artifacts:
  files:
    - .\sample\bin\obj\Debug\*
